[training_parameters]
EPOCHS = 10
LEARNING_RATE = 1e-6
CHANNELS = 12

[paths]
DRIVE = "C"
X_PATH = "C:/Users/aspence1/scripts/loc2vec_data/build_3_channel/i"
X_POS_PATH = "C:/Users/aspence1/scripts/loc2vec_data/build_3_channel/pos"
X_NEG_PATH = "NA"